Django/djangoblog/accounts/urls.py
from django.urls import path
from . import views # these two imports must be done for every urls.py file

# namespacing:
app_name = 'accounts'

# after creating these urls here, don't forget to include them in the 
# root urls file!
urlpatterns = [
    path('signup/', views.signup_view, name="signup"),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

Django/djangoblog/articles/urls.py
from django.urls import path, re_path
from . import views

"""
We still need to import views and the urlpatterns.

re_path() will allow the use of regular expressions (path() does not). 
"""

# name spacing our url file
app_name = 'articles'

# create must come above the slug, or else django will think that create is a slug
# re_path will extend the url to the name - or rather slug - of the article
urlpatterns = [
    path('', views.article_list, name="list"),
    path('create/', views.article_create, name='create'),
    re_path(r'^(?P<slug>[\w-]+)/$', views.article_detail, name="detail"),
]

Django/djangoblog/djangoblog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static  # allow django to serve up media files
from django.conf import settings  # this is from our settings.py file
from articles import views as article_views

"""
This is where we control routes/how we send users to different pages

urls.py has the following jobs:
    -look at the request URL from the browser
    -decide which function to fire in views.py
    -views.py will then run the function, which will control what the user
     sees when they visit that url in the browser (i.e some html template)

need to create a url that will include urls from other apps in order
to register the url(s) of other apps this is done by using the following 
code:
            'path(name_of_route, include(name_of_app.urls))
    -note that name_of_route and name_of_app.urls must be strings
    -also note that the name_of_route should probably something like app_name/
     such that future urls created in the app will extend off of app_name/
     (i.e a url of about in the new app will then be app_name/about/)

This is where we will tell Django to serve up our static files
"""

urlpatterns = [
    path('admin/', admin.site.urls), # created and shipped by Django for you (our admin section)
    path('about/', views.about, name='about'),
    path('', article_views.article_list, name='home'),  # editing home page so that we go to the articles list
    path('articles/', include("articles.urls")), # will include urls from our articles app
    path('accounts/', include("accounts.urls")), # will include urls from our accounts app
]

# tells django where to serve the static files
urlpatterns += staticfiles_urlpatterns()

# tells django where to serve the media files
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django/djangoblog/articles/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

"""
This file is automatically generated with apps

model files serve as a way to get records from a DB

A model is represented by a class in Django
    -by convention the name of the class starts with
     a capital letter

model filed types
    -will give Django an idea of what is stored (in terms of
     data type)
    -a charField is a small amount of text
    -a textField is a large amount of text

After a model is creating, it must be migrated to the DB
so that the DB is aware of the existence of the model - the
DB will then be aware to create the table that the model 
has described in the class

You first need to create a migration file before migrating. This
will track the changes that occur to the model file. This will be
responsible for updating the DB.

To create the migration file use the following command:
    python3 manage.py makemigrations

In order to associate a user with an article for the author field,
we need to use a foreign key. A foreign key is a way to associate
a record from one model (in this case the article model) with a record
from another model (in this case the user model).
"""
class Article(models.Model):
    # class properties
    title = models.CharField(max_length=100) 
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True) # automatically populates this field with now time
    thumb = models.ImageField(default='default.png', blank=True)
    author = models.ForeignKey(User, default=None, on_delete=models.DO_NOTHING,)

    # self will be the instance of the article
    def __str__(self):
        """
        This should return the title of an instance of an Article
        when we get the article objects from the server.

        So Article.objects.all() will return the title of the articles
        rather than something useless like 'Article object (1)'
        """
        return self.title

    def snippet(self):
        """
        Returns a snippet of the body of a blog post

        Used for a preview of the article
        """
        return f"{self.body[:50]}..."

Django/djangoblog/articles/forms.py
from django import forms
from . import models

class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title', 'body', 'slug', 'thumb']

Django/djangoblog/articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms

# Create your views here.

"""
note templates for the articles app will be kept within
the articles folder

we typically add another folder within this local template
folder that is the name of the app - the purpose for this
is to 'namespace' templates so they will not be confused
will global templates (or other ones)

global templates (that the entire app needs) will be kept
in the templates folder in the root dir
"""

def article_list(request):
    """
    responsible for rendering our list of articles, specifically
    the template defined by the second arguement and the data
    (in the third arg) that feeds into the template
    """
    # the data we will send to the template
    articles = Article.objects.all().order_by('date')

    return render(request, 'articles/article_list.html', {'articles': articles}) # here is where namespacing is nice

def article_detail(request, slug):
    """
    """
    article = Article.objects.get(slug=slug)

    return render(request, 'articles/article_detail.html', {'article': article})

@login_required(login_url="/accounts/login/")
def article_create(request):
    """
    """
    if request.method == 'POST':
        form = forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)  # saves form to db, commit waits for saving until something is done with instance
            instance.author = request.user
            instance.save()  # now we are committing!
            return redirect('articles:list')
    else:
        form = forms.CreateArticle()
    return render(request, 'articles/article_create.html', {'form':form})

Django/djangoblog/articles/templates/articles/article_create.html
{% extends 'base_layout.html' %}

{% block content %}
    <div class="create-article">
        <h2>Create an awesome new article</h2>
        <!--
            recall the csrf_token is a security measure for post requests

            the enctype stands for encryption type, this is for encoding the form
            data that is uploaded (for the choose file)
        -->
        <form class="site-form" action="{% url 'articles:create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Create">
        </form>
    </div>
{% endblock %}

Django/djangoblog/articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="article-detail">
    <div class="article">
        <img src="{{ article.thumb.url }}"/>
        <h2>{{ article.title }}</h2>
        <p>{{ article.body }}</p>
        <p>{{ article.date }}</p>
    </div>
</div>
{% endblock %}

Django/djangoblog/articles/templates/articles/article_list.html
{% extends 'base_layout.html' %}

<!--
    template tags are a django feature that allows us to insert python
    logic into our html file - this allows us to output data

    the next step (after styling a template) is to create a base template
    s.t. if you wish to change the style of your header, it does not have
    to be done for all templates (we are modularizing)
-->

{% block content %}
    <h1>Article list</h1>
    <br>
    <div class="articles">
        {% for article in articles %}
            <div class="article">
                <!-- 
                    'detail' alone does not work here! 'detail' is looking for 
                    the slug that we have in our re_path() function, so we need
                    to pass it in. Therefore, we can pass through the name capturing
                    group (the thing b/w <> in our re_path()) parameter by saying:
                                parameter = parameter_value
                -->
                <h2><a href="{% url 'articles:detail' slug=article.slug %}">{{ article.title }}</a></h2>
                <p>{{ article.snippet }}</p>
                <p>{{ article.date }}</p>
                <p class="author">added by {{ article.author.username }}</p>
            </div>
        {% endfor %}
    </div>
{% endblock %}