Django/djangoblog/accounts/urls.py
from django.urls import path
from . import views # these two imports must be done for every urls.py file

# namespacing:
app_name = 'accounts'

# after creating these urls here, don't forget to include them in the 
# root urls file!
urlpatterns = [
    path('signup/', views.signup_view, name="signup"),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

Django/djangoblog/articles/urls.py
from django.urls import path, re_path
from . import views

"""
We still need to import views and the urlpatterns.

re_path() will allow the use of regular expressions (path() does not). 
"""

# name spacing our url file
app_name = 'articles'

# create must come above the slug, or else django will think that create is a slug
# re_path will extend the url to the name - or rather slug - of the article
urlpatterns = [
    path('', views.article_list, name="list"),
    path('create/', views.article_create, name='create'),
    re_path(r'^(?P<slug>[\w-]+)/$', views.article_detail, name="detail"),
]

Django/djangoblog/djangoblog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static  # allow django to serve up media files
from django.conf import settings  # this is from our settings.py file
from articles import views as article_views

"""
This is where we control routes/how we send users to different pages

urls.py has the following jobs:
    -look at the request URL from the browser
    -decide which function to fire in views.py
    -views.py will then run the function, which will control what the user
     sees when they visit that url in the browser (i.e some html template)

need to create a url that will include urls from other apps in order
to register the url(s) of other apps this is done by using the following 
code:
            'path(name_of_route, include(name_of_app.urls))
    -note that name_of_route and name_of_app.urls must be strings
    -also note that the name_of_route should probably something like app_name/
     such that future urls created in the app will extend off of app_name/
     (i.e a url of about in the new app will then be app_name/about/)

This is where we will tell Django to serve up our static files
"""

urlpatterns = [
    path('admin/', admin.site.urls), # created and shipped by Django for you (our admin section)
    path('about/', views.about, name='about'),
    path('', article_views.article_list, name='home'),  # editing home page so that we go to the articles list
    path('articles/', include("articles.urls")), # will include urls from our articles app
    path('accounts/', include("accounts.urls")), # will include urls from our accounts app
]

# tells django where to serve the static files
urlpatterns += staticfiles_urlpatterns()

# tells django where to serve the media files
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django/djangoblog/templates/about.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>About</title>
    </head>
    <body>
        <h1>This is the about page</h1>
        <p>We like Django!</p>
    </body>
</html>

Django/djangoblog/templates/base_layout.html
{% load static %}

<!--
    This is our base layout that will be repeated throughout the 
    project. This will reduce redundant html code, and any new code
    will be added as the block content.
-->

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Articles</title>
        <link rel="stylesheet" href="{% static 'styles.css' %}">
    </head>
    <body>
        <header class="wrapper">
            <h1><a href="{% url 'home' %}"><img src="{% static 'logo.png' %}"/></a></h1>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                    <li>
                        <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                            {% csrf_token %}
                            <button type="submit">Logout</button>
                        </form>
                        <li><a href="{% url 'articles:create' %}" class="highlight">New Article</a></li>
                    </li>
                    {% else %}
                        <li><a href="{% url 'accounts:login' %}">Login</a></li>
                        <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
                    {% endif %}
                </ul>
            </nav>
            <div class="wrapper">
                {% block content %}
                {% endblock %}
            </div>
        </header>
    </body>
</html>

Django/djangoblog/templates/home.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Home</title>
    </head>
    <body>
        <h1>This is the home page</h1>
        <p>Welcome to Djangoblog!</p>
    </body>
</html>